version: '3.7'

services:
  database:
    container_name: 'cartapp_database'
    image: 'mysql:8.0.27'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'dbpass'
      MYSQL_DATABASE: "dbname"
    ports:
      - "3306:3306"
  cartapp:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: cartapp
    volumes:
      - ./:/var/www/backend_app
    ports:
      - "8000:80"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - database